# Generated by Django 3.2.5 on 2021-07-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='radioaficionados',
            fields=[
                ('indicativo', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=25)),
                ('apellidoP', models.CharField(max_length=25)),
                ('apellidoM', models.CharField(max_length=25)),
                ('municipio', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='bitacoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('enlace', models.CharField(blank=True, max_length=10)),
                ('estacion_rec', models.CharField(blank=True, max_length=10)),
                ('grid', models.CharField(blank=True, max_length=5)),
                ('freq', models.FloatField()),
                ('modulacion', models.CharField(blank=True, max_length=10)),
                ('reporte1', models.CharField(blank=True, max_length=10)),
                ('reporte2', models.CharField(blank=True, max_length=10)),
                ('indicativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.radioaficionados')),
            ],
        ),
    ]
