# Generated by Django 3.2.5 on 2021-07-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_radioaficionados_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radioaficionados',
            name='last_login',
        ),
    ]
