# Generated by Django 3.2.5 on 2021-07-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_estaciones_terrenas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estaciones_terrenas',
            name='tipo_antena',
            field=models.CharField(max_length=20),
        ),
    ]
