# Generated by Django 3.2.5 on 2021-07-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_estaciones_terrenas_modulacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoras',
            name='nombre_estacion',
            field=models.CharField(default='Sin Estacion', max_length=30),
        ),
    ]
