# Generated by Django 3.2.5 on 2021-07-24 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_bitacoras_nombre_estacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=600)),
                ('indicativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.radioaficionados')),
            ],
        ),
    ]
