# Generated by Django 3.2.5 on 2021-08-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_estaciones_terrenas_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensajeadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuerpoMsg', models.CharField(max_length=600)),
            ],
        ),
    ]
