# Generated by Django 3.2.5 on 2021-08-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_radioaficionados_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacoras',
            name='mensaje4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='bitacoras',
            name='mensaje5',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
